spring.application.name=security
spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=root@39

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=R9v8A4kL7mT2qN1pX5yE0zD3sC6wV8bB1nN4mJ9kH7gD5fS3dA2pQ9oI8uU7yY6tT5rR4eE3wW2qQ1aA0zZ9xX8cC7vV6bB5nN4mM3jJ2kK1hH0gG9fF8dD7sS6aA5qQ4wW3eE2rR1tT0
jwt.expiration=86400000